extends: airbnb

env:
  node: true
  es6: true
  jest: true

parser: "babel-eslint"

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

plugins:
  - jest

rules:
  import/no-unresolved:
    - 2
    - ignore:
      - "^~"
      - "^@"
  import/extensions:
    - 0
  import/no-extraneous-dependencies:
    - 0
  import/prefer-default-export:
    - 0
  react/prefer-stateless-function:
    - 0
  react/jsx-filename-extension:
    - 0
  react/jsx-max-props-per-line:
    - 2
    - maximum: 2
  react/forbid-prop-types:
    - 0
  react/no-array-index-key:
    - 0
  jsx-a11y/no-static-element-interactions:
    - 0
  jest/no-disabled-tests:
    - warn
  jest/no-focused-tests:
    - error
  arrow-parens:
    - 2
    - always
  newline-after-var:
    - 2
    - always
  newline-before-return:
    - 2
  newline-per-chained-call:
    - 2
    -
      ignoreChainWithDepth: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxEOF: 0
  comma-dangle:
    - error
    - never
  quote-props:
    - error
    - consistent-as-needed
  max-len:
    - 2
    - code: 150
  no-use-before-define: off
  no-underscore-dangle:
    - error
  eol-last: error
  class-methods-use-this:
    - 0
  jsx-a11y/click-events-have-key-events:
    - 0
  jsx-a11y/no-noninteractive-element-interactions:
    - 0
  jsx-a11y/anchor-is-valid:
    - 0

globals:
  expect: true
  window: true
  document: true
  isDev: true
